config/routes.rb
Rails.application.routes.draw do


  resources :perf_review_requests
  resources :perf_reviews
  resources :ques_answs
  resources :perf_review_catgs do
    resources :review_catg_quests, only: [:new, :create]
  end

  resources :review_catg_quests, only: [:edit, :update, :destroy]

  resources :events
  root 'home#index'
  resources :project_team_members
  get "/org_team_chart" => "project_team_members#org_team_chart", as: :org_team_chart
  resources :project_teams
  resources :trackers
  resources :projects
  resources :leaves
  resources :issues
  resources :experiences
  resources :employees, except: [:show], path: '/users'
  resources :leave_work_assign
  resources :roles

  devise_for :employees, controllers: {
    sessions: 'employees/sessions',
    registrations: 'employees/registrations',
    passwords: 'employees/passwords',
  }

  devise_for :employee, :controllers => {:sessions => 'sessions'}, :skip => [:sessions] do
    get '/employee/sign_in' => 'sessions#new', :as => :new_emoloyee_session
    post '/employee/sign_in' => 'sessions#create', :as => :employee_session
    get '/employee/sign_out' => 'sessions#destroy', :as => :destroy_employee_session
  end

  get 'leave_requests' => "leave_requests#index"
  get 'home/index'

  get 'home/about'

  get 'home/contact'

  get '/dashboard' => 'dashboard#index', as: :dashboard

  get 'reports/index'
  get 'reports/team_comparision' => "reports#team_comparision", as: :team_comparision
  get 'reports/team_highest_score' => "reports#team_highest_score", as: :team_highest_score
  get 'reports/attemted_vs_passed' => "reports#attemted_vs_passed", as: :attemted_vs_passed
  get 'reports/result_employee_list' => "reports#result_employee_list", as: :report_employee_list
  get 'reports/show_exam_attempte/:employee_id' => "reports#show_exam_attempte", as: :show_exam_attempte
  get 'reports/export_to_csv' => "reports#export_to_csv", as: :export_to_csv

  get 'teams/add_members/:id/:employee_id' => "teams#add_members", as: :add_members
  get 'teams/remove_members/:id/:employee_id' => "teams#remove_members", as: :remove_members
  resources :teams

  resources :subjects
  # get  'results/index' => "results#index", as: :index
  get  'results/exam_result/:exam_id' => "results#exam_result", as: :exam_result
  get  'results/employee_result(/:employee_id)' => "results#employee_result", as: :employee_result
  post 'results/filter_result' => "results#filter_result", as: :filter_result
  get  'results/print/:result' => "results#print", as: :print
  get  'results/activate_result/:exam_id' => "results#activate_result", as: :activate_result
  get  'results/inactivate_result/:exam_id' => "results#inactivate_result", as: :inactivate_result
  get  'results/print_team_result/:team_id' => "results#print_team_result", as: :print_team_result

  post 'questions/complete'

  resources :results
  resources :questions
  resources :exams
  resources :switch_days


  post '/employee_report_show' => "reports#employee_report_show", as: :employee_report_show
  get '/employee_report' => "reports#employee_report", as: :employee_report
  get '/start_tracker_timer' => "trackers#start_tracker_timer", as: :start_tracker_timer
  get '/stop_tracker_timer' => "trackers#stop_tracker_timer", as: :stop_tracker_timer
  get '/employee_projects' => "trackers#employee_projects", as: :employee_projects
  get '/attendance' => "employees#attendance_logs", as: :attendance_logs
  #get '/switch_day' => "employees#switch_day", as: :switch_day
  get '/exam/questions/:exam_id' => "questions#start", as: :exam_start
  post '/question/submit/:q_id' => "questions#save_ans", as: :save_ans
  get '/question/save_ans_by_teacher/:q_id/:employee_id' => "questions#save_ans_by_teacher", as: :save_ans_by_teacher

  resources :documents
  get '/profile/:id' => "employees#show", as: :employee_profile
  post '/upload_document/:id' => "employees#upload_document", as: :upload_document
  get 'download/:id' => "documents#download", as: :download_document
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html'
  get '/gen/send_message' => 'general#send_message', as: :general_send_message
  get '/gen/show_message/:m_id' => 'general#show_message', as: :general_show_message
  get '/gen/new_message' => 'general#new_message', as: :general_new_message
  delete '/gen/delete_message/:m_id' => 'general#delete_message', as: :delete_message


  get '/:id/signatures' => "signatures#index", as: :user_signatures
  post '/save_signature/:id' => "signatures#create", as: :save_signature
  get '/signatures/:id/download' => "signatures#download", as: :download_signature
  delete '/signatures/:id' => "signatures#destroy", as: :delete_signature

  get '/employee_benefits' => 'employee_benefits#index', as: :employee_benefits
  post '/employee_benefits/:id/upload_template' => "employee_benefits#upload_template", as: :upload_template
  get '/download_template/:id' => "employee_benefits#download_emp_benefit_doc", as: :download_emp_benefit_doc
  post '/employee_benefits/:id/upload_benefit_doc' => "employee_benefits#upload_benefit_doc", as: :upload_benefit_doc
  delete '/employee_benefit_docs/:id/destroy' => "employee_benefits#delete_emp_benefit_doc", as: :delete_emp_benefit_doc
  get '/employee_benefit_docs/:id' => "employee_benefits#show", as: :show_emp_benefit_doc

  get '/disclosures' => 'disclosures#index', as: :disclosures
  post '/disclosures/:id/upload_disclosure_template' => "disclosures#upload_disclosure_template", as: :upload_disclosure_template
  get '/download_disc_template/:id' => "disclosures#download_disclosure_doc", as: :download_disclosure_doc
  post '/disclosures/:id/upload_disclosure_doc' => "disclosures#upload_disclosure_doc", as: :upload_disclosure_doc
  delete '/disclosures/:id/destroy' => "disclosures#delete_disclosure_doc", as: :delete_disclosure_doc
  get '/disclosures/:id' => "disclosures#show", as: :show_disclosure_doc

  get '/perf_review_template/new' => 'perf_review_templates#new', as: :new_perf_review_template

  get '/request/:reviewer_id/send_review' => 'perf_reviews#new', as: :give_review

  post '/create_perf_reviews/:reviewer_id' => 'perf_reviews#create', as: :create_perf_reviews

  get '/download_perf_review/:id' => 'perf_reviews#download_pdf', as: :download_pdf

  mount ActionCable.server => "/cable"
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :skills

  belongs_to :role
  has_many :leaves, class_name: "Leave", foreign_key: "employee_id"
  has_many :leave_work_emps, class_name: "LeaveWorkAssign", foreign_key: "employee_id"
  has_many :events, class_name: "Event", foreign_key: "employee_id_id"
  has_many :switch_days, class_name: "SwitchDay", foreign_key: "employee_id"
  has_many :exams, through: :teams
  has_many :results
  has_many :issues, class_name: "Issue", foreign_key: "creator_id"
  has_many :responses
  has_many :employee_usage_logs
  has_many :trackers, class_name: "Tracker", foreign_key: "employee_id"

  belongs_to :role
  has_many :teams, through: :team_members
  has_many :team_members
  has_many :leave, as: :applicable
  has_many :documents, dependent: :destroy
  has_many :experiences, dependent: :destroy
  has_one :project_team_member, dependent: :destroy

  has_many :signatures, dependent: :destroy
  has_many :emp_benefit_docs, dependent: :destroy
  has_many :disclosures, dependent: :destroy

  has_many :review_categories, class_name: "PerfReviewCatg", foreign_key: "employee_id"
  has_many :answers, class_name: "QuesAnsw", foreign_key: "employee_id"

  # has_one :project_team, through: :project_team_members
  # has_many :project_team_members

  scope :employees, -> { joins(:role).where(roles: { role: "employee" }) }
  scope :team_managers, -> { joins(:role).where(roles: { role: "team_member" }) }
  scope :team_leaders, -> { joins(:role).where(roles: { role: "team_leader" }) }

  scope :team_members, -> { joins(:role).where(roles: { role: "team_member" }) }
  scope :hr, -> { joins(:role).where(roles: { role: "hr" }) }
  scope :president, -> { joins(:role).where(roles: { role: "president" }) }
  scope :team_exams, -> { }

  scope :members, -> { joins(:role).where("roles.role in (?)", ["employee", "team_manager", "team_leader"]) }

  def self.not_added()
    includes(:project_team_member).where(project_team_members: { employee_id: nil } )
  end

  def user_role
    role.role
  end

  def president?
    user_role == 'president'
  end

  def hr?
    user_role == "hr"
  end

  def team_manager?
    user_role == "team_manager"
  end

  def team_leader?
    user_role == "team_leader"
  end

  def employee?
    user_role == "employee"
  end

  def name
    if first_name.present? || last_name.present?
      "#{first_name} #{last_name}"
    else
      email
    end
  end

  def self.to_csv
    CSV.generate(headers: true) do |csv|
      csv << ["Employee", "Exam", "Attemted?"]

      all.each do |user|
        user.exams.each do |exam|
          csv << [ "#{user.fullname}", "#{exam.title}", "#{exam.is_attemted_by(user)}" ]
        end
      end
    end
  end

  def any_reviews_pending?
    reviews_pending.present?
  end

  def reviews_pending
    PerfReviewReviewer.where(reviewer_id: self.id, flag: false)
  end

  def reviews_pending_for
    arr = Array.new
    reviews_pending.each do |review_pending|
      arr << review_pending.perf_review_request.reviewee_id
    end
    arr.map { |id| Employee.find(id).email }
  end

end

app/controllers/employees/confirmations_controller.rb
class Employees::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  layout 'authentication'
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employees/omniauth_callbacks_controller.rb
class Employees::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employees/passwords_controller.rb
class Employees::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  layout 'authentication'
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employees/registrations_controller.rb
class Employees::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  
  layout 'authentication'

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :mobile, :address, :city, :state, :country, :zipcode, :role_id])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :mobile, :address, :city, :state, :country, :zipcode, :role_id])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employees/sessions_controller.rb
class Employees::SessionsController < Devise::SessionsController
   before_action :configure_sign_in_params, only: [:create]
  @@employee=nil
  layout 'authentication'
  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
     super  
     @@employee = Employee.find_by_email(sign_in_params[:email])

    if @@employee.employee_usage_logs.present? 
      if @@employee.employee_usage_logs.last.entry_type != "IN" 
       EmployeeUsageLog.create(employee_id: @@employee.id,entry_type: "IN" )
     else
       EmployeeUsageLog.create(employee_id: @@employee.id,entry_type: "IN" )
     end
   end
   end

  # DELETE /resource/sign_out
   def destroy
     super
     EmployeeUsageLog.create(employee_id: @@employee.id,entry_type: "OUT") if @@employee.present?
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
   end
end

app/controllers/employees/unlocks_controller.rb
class Employees::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy, :upload_document]
  def index
    if current_employee.president?
      @employees = Employee.all
    elsif current_employee.hr?
      @employees = Employee.where.not(role_id: Role.where(role: 'president').ids)
    elsif current_employee.team_leader?
      @employees = Employee.where.not(role_id: Role.where(role: ['president', 'hr']).ids)
    end
  end

  def show
    @experience = Experience.new
  end

  def attendance_logs

    # _month_report = []
    swith_dates = current_employee.switch_days.map(&:real_date)  
    logs=current_employee.employee_usage_logs.where("DATE(created_at) = ?", Date.today)
    if logs.present?
      @remark = logs.where(entry_type: "IN").first.logs_time if logs.where(entry_type: "IN").first.logs_time.present?
    end 
    if logs.where(entry_type: "IN").first.present? && logs.where(entry_type: "OUT").last.present?
	    start_time = logs.in_log
	    end_time =  logs.out_log
    else
       start_time = 0
       end_time = 0 
    end
      if start_time.present? && end_time.present?
        @minutes = time_diff(start_time, end_time).abs
      end

         total_seconds = @minutes * 60
         @hours = total_seconds / (60 * 60)
         @minutes = (total_seconds / 60) % 60
         @seconds = total_seconds % 60
  end

  def edit
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update
    if @employee.update(employee_params)
      flash[:notice] = 'Exam was successfully updated.'
    end
    redirect_to employees_path
  end

  def upload_document
    if params[:documents]
      params[:documents].each { |document|
        @employee.documents.create(document: document)
      }
    end
    redirect_to employee_profile_path(@employee)
  end

  private

    def set_employee
      @employee = Employee.find(params[:id])
    end


    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :email, :role_id)
    end

    def time_diff(start_time, end_time)
        (start_time -  end_time) / 60
    end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<tr>
  <td><%= employee.name if employee.present? %></td>
  <td><%= link_to 'Add', add_members_path(team, employee), remote: true %></td>
</tr>

app/views/employees/_form.html.erb
<%= form_for(employee) do |f| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-sm-6 col-xs-12">
    <div class="form-group form-float">
      <div class="form-line">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-xs-12">
    <div class="form-group form-float">
      <div class="form-line">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-xs-12">
    <div class="form-group form-float">
      <div class="form-line">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control", disabled: true %>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-xs-12">
    <div class="form-group form-float">
      <div class="form-line">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-xs-12">
    <div class="form-group form-float">
      <div class="form-line">
        <%= f.label :city %>
        <%= f.text_field :city, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-xs-12">
    <div class="form-group form-float">
      <div class="form-line">
        <%= f.label :state %>
        <%= f.text_field :state, class: "form-control" %>
      </div>
    </div>
  </div>

<div class="col-sm-6 col-xs-12">
    <div class="form-group form-float">
      <div class="form-line">
        <%= f.label :country %>
        <%= f.text_field :country, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-xs-12">
    <div class="form-group form-float">
      <div class="form-line">
        <%= f.label :zipcode %>
        <%= f.text_field :zipcode, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-xs-12">
    <div class="form-group form-float">
      <div class="form-line">
        <%= f.label :role_id %>
        <%= f.select :role_id, Role.all.collect {|r| [ r.role, r.id ] }, {}, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Save Employee", class: "btn bg-blue waves-button-input" %>
  </div>
<% end %>

app/views/employees/attendance_logs.html.erb
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>Attandance Logs</h2>
      </div>
      <div class="body">
        <div class="body table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th>Date</th>
                <th>Hours : Minutes : Second </th>
                <th>Remark</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">1</th>
                <td><%=Date.today-1%></td>
                <td><%= @hours.floor%>:<%=@minutes.floor%>:<%=@seconds.floor%></td>
                <td><%= @remark %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<button type="button" class="btn btn-default" data-toggle="modal" data-target="#largeModal">MODAL - LARGE SIZE</button>
<div class="modal fade" id="largeModal" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="largeModalLabel">Modal title</h4>
                        </div>
                        <div class="modal-body">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sodales orci ante, sed ornare eros vestibulum ut. Ut accumsan
                            vitae eros sit amet tristique. Nullam scelerisque nunc enim, non dignissim nibh faucibus ullamcorper.
                            Fusce pulvinar libero vel ligula iaculis ullamcorper. Integer dapibus, mi ac tempor varius, purus
                            nibh mattis erat, vitae porta nunc nisi non tellus. Vivamus mollis ante non massa egestas fringilla.
                            Vestibulum egestas consectetur nunc at ultricies. Morbi quis consectetur nunc.
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-link waves-effect">SAVE CHANGES</button>
                            <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
                        </div>
                    </div>
                </div>
            </div>

app/views/employees/edit.html.erb
<div class="row clearfix">
  <div class="col-sm-12">
    <div class="card">
      <div class="header">
        <h2>Editing Employee</h2>
      </div>
      <div class="body">
        <div class="row clearfix">
          <div class="col-sm-6 col-sm-offset-2 col-xs-12">
            <%= render 'form', employee: @employee %>
          </div>
        </div>
        <%= link_to 'Show', @employee %> |
        <%= link_to 'Back', employees_path %>
      </div>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>
          Employees
          <small>Show/Edit/Delete</small>
          
        </h2>
      </div>
      <% if @employees.present? %>
      <div class="body table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @employees.each do |employee| %>
                <tr>
                  <td><%= employee.name %></td>
                  <td><%= employee.email %></td>
                  <td><%= employee.user_role %></td>
                  <% if current_employee.user_role != 'employee' %>
                    <td><%= link_to 'Show', employee_profile_path(employee) %></td>
                    <td><%= link_to 'Edit', edit_employee_path(employee
                    ) %></td>
                    <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        You don't have any exam
      <% end %>
      <br/>
    </div>
  </div>
</div>

app/views/employees/show.html.erb
<div class="row clearfix js-sweetalert">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <p id="notice"><%= notice %></p>
      <div class="header">
        <h2>
          <div class="row clearfix">
            <div class="col-xs-12">
              <strong>Employee:</strong>
              <%= @employee.name %>
            </div>
            <br/>
            <div class=" col-md-6 col-sm-6 col-xs-12">
              <strong>Email:</strong>
              <%= @employee.email %>
            </div>
            <div class=" col-md-6 col-sm-6 col-xs-12">
              <strong>Role:</strong>
              <%= @employee.user_role %>
            </div>
          </h2>
        </h2>
      </div>
      <%= link_to "Change your password", edit_employee_registration_path %>
      <div class="body">

        <div class="row clearfix">
          <div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
            <h2 class='text-center'>Document Upload</h2>
            <%= form_for(@employee, url: upload_document_path(@employee), method: :post, html: { multipart: true }) do |f| %>

              <div class="col-xs-12">
                <div class="form-group form-float">
                  <div class="form-line">
                    <%= file_field_tag "documents[]", type: :file, multiple: true %>
                  </div>
                </div>
              </div>
              <div class="form-actions">
                <%= f.submit 'Upload', :class => 'btn btn-primary' %>
              </div>
            <% end %>
          </div>
        </div>


        <div class="row clearfix">
          <div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
            <div class="table-responsive">
              <h1>Documents</h1>
              <table class="table table-bordered table-hover table-striped">
                <thead>
                  <tr>
                    <th>File Name</th>
                    <th colspan="2"></th>
                  </tr>
                </thead>
                <tbody>
                  <% @employee.documents.each do |document| %>
                    <tr>
                      <td><%=  document.document_file_name %></td>
                      <% if current_employee.user_role != 'employee' %>
                        <td><%= link_to 'download', download_document_path(document), target: "blank" %></td>
                        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      <% end %>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>


        <hr/>
        <hr/>
        <div class="row clearfix">
          <div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
            <h2 class='text-center'> Experience </h2>
            <%= form_for(@experience, url: experiences_path, method: :post) do |f| %>
              <%= f.hidden_field :employee_id, value: @employee.id %>
              <div class="col-xs-12">
                <div class="form-group form-float">
                  <div class="form-line">
                    <%= f.label :title, class: "form-label" %>
                    <%= f.text_field :title, class: "form-control" %>
                  </div>
                </div>
              </div>
              <div class="col-xs-12">
                <div class="form-group form-float">
                  <div class="form-line">
                    <%= f.label :description, class: "form-label" %>
                    <%= f.text_area :description, class: "form-control", placeholder: "Job Description" %>
                  </div>
                </div>
              </div>
              <div class="col-xs-12">
                <div class="form-group form-float">
                  <div class="form-line">
                    <%= f.label :from_date %>
                    <%= f.text_field :from_date, class: "form-control datepicker" %>
                  </div>
                </div>
              </div>
              <div class="col-xs-12">
                <div class="form-group form-float">
                  <div class="form-line">
                    <%= f.label :to_date %>
                    <%= f.text_field :to_date, class: "form-control datepicker" %>
                  </div>
                </div>
              </div>

              <div class="form-actions">
                <%= f.submit 'Add Experience', :class => 'btn btn-primary' %>
              </div>
            <% end %>
          </div>
        </div>

        <hr/>

        <div class="row clearfix">
          <div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
            <div class="table-responsive">
              <h1>Experiences</h1>
              <table class="table table-bordered table-hover table-striped">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>From Date</th>
                    <th>To Date</th>

                    <th colspan="2"></th>
                  </tr>
                </thead>
                <tbody>
                  <% @employee.experiences.each do |experience| %>
                    <tr>
                      <td><%= experience.title %></td>
                      <td><%= experience.description %></td>
                      <td><%= experience.from_date %></td>
                      <td><%= experience.to_date %></td>
                      <td><%= link_to 'edit', edit_experience_path(experience) %></td>
                      <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>

                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <%= link_to 'Edit', edit_employee_path(@employee) %> |
        <%= link_to 'Back', employees_path %>

        <% content_for :page_script do %>
          <script type="text/javascript">
            $("#experience_from_date, #experience_to_date").datepicker()
          </script>
        <% end %>