config/routes.rb
Rails.application.routes.draw do


  resources :perf_review_requests
  resources :perf_reviews
  resources :ques_answs
  resources :perf_review_catgs do
    resources :review_catg_quests, only: [:new, :create]
  end

  resources :review_catg_quests, only: [:edit, :update, :destroy]

  resources :events
  root 'home#index'
  resources :project_team_members
  get "/org_team_chart" => "project_team_members#org_team_chart", as: :org_team_chart
  resources :project_teams
  resources :trackers
  resources :projects
  resources :leaves
  resources :issues
  resources :experiences
  resources :employees, except: [:show], path: '/users'
  resources :leave_work_assign
  resources :roles

  devise_for :employees, controllers: {
    sessions: 'employees/sessions',
    registrations: 'employees/registrations',
    passwords: 'employees/passwords',
  }

  devise_for :employee, :controllers => {:sessions => 'sessions'}, :skip => [:sessions] do
    get '/employee/sign_in' => 'sessions#new', :as => :new_emoloyee_session
    post '/employee/sign_in' => 'sessions#create', :as => :employee_session
    get '/employee/sign_out' => 'sessions#destroy', :as => :destroy_employee_session
  end

  get 'leave_requests' => "leave_requests#index"
  get 'home/index'

  get 'home/about'

  get 'home/contact'

  get '/dashboard' => 'dashboard#index', as: :dashboard

  get 'reports/index'
  get 'reports/team_comparision' => "reports#team_comparision", as: :team_comparision
  get 'reports/team_highest_score' => "reports#team_highest_score", as: :team_highest_score
  get 'reports/attemted_vs_passed' => "reports#attemted_vs_passed", as: :attemted_vs_passed
  get 'reports/result_employee_list' => "reports#result_employee_list", as: :report_employee_list
  get 'reports/show_exam_attempte/:employee_id' => "reports#show_exam_attempte", as: :show_exam_attempte
  get 'reports/export_to_csv' => "reports#export_to_csv", as: :export_to_csv

  get 'teams/add_members/:id/:employee_id' => "teams#add_members", as: :add_members
  get 'teams/remove_members/:id/:employee_id' => "teams#remove_members", as: :remove_members
  resources :teams

  resources :subjects
  # get  'results/index' => "results#index", as: :index
  get  'results/exam_result/:exam_id' => "results#exam_result", as: :exam_result
  get  'results/employee_result(/:employee_id)' => "results#employee_result", as: :employee_result
  post 'results/filter_result' => "results#filter_result", as: :filter_result
  get  'results/print/:result' => "results#print", as: :print
  get  'results/activate_result/:exam_id' => "results#activate_result", as: :activate_result
  get  'results/inactivate_result/:exam_id' => "results#inactivate_result", as: :inactivate_result
  get  'results/print_team_result/:team_id' => "results#print_team_result", as: :print_team_result

  post 'questions/complete'

  resources :results
  resources :questions
  resources :exams
  resources :switch_days


  post '/employee_report_show' => "reports#employee_report_show", as: :employee_report_show
  get '/employee_report' => "reports#employee_report", as: :employee_report
  get '/start_tracker_timer' => "trackers#start_tracker_timer", as: :start_tracker_timer
  get '/stop_tracker_timer' => "trackers#stop_tracker_timer", as: :stop_tracker_timer
  get '/employee_projects' => "trackers#employee_projects", as: :employee_projects
  get '/attendance' => "employees#attendance_logs", as: :attendance_logs
  #get '/switch_day' => "employees#switch_day", as: :switch_day
  get '/exam/questions/:exam_id' => "questions#start", as: :exam_start
  post '/question/submit/:q_id' => "questions#save_ans", as: :save_ans
  get '/question/save_ans_by_teacher/:q_id/:employee_id' => "questions#save_ans_by_teacher", as: :save_ans_by_teacher

  resources :documents
  get '/profile/:id' => "employees#show", as: :employee_profile
  post '/upload_document/:id' => "employees#upload_document", as: :upload_document
  get 'download/:id' => "documents#download", as: :download_document
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html'
  get '/gen/send_message' => 'general#send_message', as: :general_send_message
  get '/gen/show_message/:m_id' => 'general#show_message', as: :general_show_message
  get '/gen/new_message' => 'general#new_message', as: :general_new_message
  delete '/gen/delete_message/:m_id' => 'general#delete_message', as: :delete_message


  get '/:id/signatures' => "signatures#index", as: :user_signatures
  post '/save_signature/:id' => "signatures#create", as: :save_signature
  get '/signatures/:id/download' => "signatures#download", as: :download_signature
  delete '/signatures/:id' => "signatures#destroy", as: :delete_signature

  get '/employee_benefits' => 'employee_benefits#index', as: :employee_benefits
  post '/employee_benefits/:id/upload_template' => "employee_benefits#upload_template", as: :upload_template
  get '/download_template/:id' => "employee_benefits#download_emp_benefit_doc", as: :download_emp_benefit_doc
  post '/employee_benefits/:id/upload_benefit_doc' => "employee_benefits#upload_benefit_doc", as: :upload_benefit_doc
  delete '/employee_benefit_docs/:id/destroy' => "employee_benefits#delete_emp_benefit_doc", as: :delete_emp_benefit_doc
  get '/employee_benefit_docs/:id' => "employee_benefits#show", as: :show_emp_benefit_doc

  get '/disclosures' => 'disclosures#index', as: :disclosures
  post '/disclosures/:id/upload_disclosure_template' => "disclosures#upload_disclosure_template", as: :upload_disclosure_template
  get '/download_disc_template/:id' => "disclosures#download_disclosure_doc", as: :download_disclosure_doc
  post '/disclosures/:id/upload_disclosure_doc' => "disclosures#upload_disclosure_doc", as: :upload_disclosure_doc
  delete '/disclosures/:id/destroy' => "disclosures#delete_disclosure_doc", as: :delete_disclosure_doc
  get '/disclosures/:id' => "disclosures#show", as: :show_disclosure_doc

  get '/perf_review_template/new' => 'perf_review_templates#new', as: :new_perf_review_template

  get '/request/:reviewer_id/send_review' => 'perf_reviews#new', as: :give_review

  post '/create_perf_reviews/:reviewer_id' => 'perf_reviews#create', as: :create_perf_reviews

  get '/download_perf_review/:id' => 'perf_reviews#download_pdf', as: :download_pdf

  mount ActionCable.server => "/cable"
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :trackers, class_name: "Tracker", foreign_key: "project_id"	 
  belongs_to :project_team, foreign_key: :assigned_to
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :assigned_to, :client)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-xs-12">
    <div class="form-group form-float">
      <div class="form-line">
        <%= f.label :name, class: "form-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="col-xs-12">
    <div class="form-group form-float">
      <div class="form-line">
        <%= f.label :assigned_to, "Assign to Team" %>
        <%= f.select :assigned_to, ProjectTeam.all.collect {|p| [ p.name, p.id ] }, {}, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="col-xs-12">
    <div class="form-group form-float">
      <div class="form-line">
        <%= f.label :client, class: "form-label" %>
        <%= f.text_field :client, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="actions demo-button-sizes">
    <div class="col-xs-6 col-sm-3 col-md-2 col-lg-2">
      <%= f.submit "Add", class: "btn bg-cyan waves-effect" %>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="row clearfix">
  <div class="col-sm-12">
    <div class="card">
      <div class="header">
        <h2>Projects</h2>
      </div>
      <div class="body">
        <div class="table-responsive">
          <table class="table table-bordered table-hover table-striped dataTable js-exportable">
            <thead>
              <tr>
                <th>Name</th>
                <th>Assigned to</th>
                <th>Client</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @projects.each do |project| %>
                <tr>
                  <td><%= project.name %></td>
                  <td><%= project.assigned_to %></td>
                  <td><%= project.client %></td>
                  <td><%= link_to 'Show', project %></td>
                  <td><%= link_to 'Edit', edit_project_path(project) %></td>
                  <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <br>
          <%= link_to 'New Project', new_project_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="row clearfix">
  <div class="col-sm-12">
    <div class="card">
      <div class="header">
        <h2>New Project</h2>
      </div>
      <div class="body">
        <div class="row clearfix">
          <div class="col-sm-6 col-sm-offset-2 col-xs-12">
            <%= render 'form', project: @project %>
          </div>
        </div>
        <%= link_to '< Back', projects_path %>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="row clearfix">
  <div class="col-sm-12">
    <div class="card">
      <div class="header">
        <h2>Project</h2>
      </div>
      <div class="body">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Name:</strong>
          <%= @project.name %>
        </p>

        <p>
          <strong>Assigned to:</strong>
          <% if @project.project_team.present? %>
            <%= @project.project_team.name %>
          <% end %>
        </p>

        <p>
          <strong>Client:</strong>
          <%= @project.client %>
        </p>

        <%= link_to 'Edit', edit_project_path(@project) %> |
        <%= link_to 'Back', projects_path %>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="row clearfix">
  <div class="col-sm-12">
    <div class="card">
      <div class="header">
        <h2>Project Team</h2>
      </div>
      <div class="body">
        <%if @project.project_team.present?%>
          <%@project_team = @project.project_team%>
          <p>
            <strong>Name:</strong>
            <%= @project_team.name %>
          </p>
          <%= link_to "Add Team Member", new_project_team_member_path(pt: @project_team), class: "btn bg-light-blue waves-effect" %>
          <br/>
          <br/>
          <h4>Project Team Members</h4>
          <table class="table table-bordered table-hover table-striped">
            <thead>
              <tr>
                <td> Member Name </td>
                <td> Member Role </td>
              </tr>
            </thead>
            <tbody>
              <%@project_team.project_team_members.each do |member| %>
                <tr>
                  <td><%= member.employee.name %></td>
                  <td><%= member.employee.user_role %></td>
                </tr>
              <%end%>
            </tbody>
          </table>
        <%else%>
          <%= link_to "New Project Team",  new_project_team_path %>
        <%end%>
      </div>
    </div>
  </div>
</div>