config/routes.rb
Rails.application.routes.draw do


  resources :perf_review_requests
  resources :perf_reviews
  resources :ques_answs
  resources :perf_review_catgs do
    resources :review_catg_quests, only: [:new, :create]
  end

  resources :review_catg_quests, only: [:edit, :update, :destroy]

  resources :events
  root 'home#index'
  resources :project_team_members
  get "/org_team_chart" => "project_team_members#org_team_chart", as: :org_team_chart
  resources :project_teams
  resources :trackers
  resources :projects
  resources :leaves
  resources :issues
  resources :experiences
  resources :employees, except: [:show], path: '/users'
  resources :leave_work_assign
  resources :roles

  devise_for :employees, controllers: {
    sessions: 'employees/sessions',
    registrations: 'employees/registrations',
    passwords: 'employees/passwords',
  }

  devise_for :employee, :controllers => {:sessions => 'sessions'}, :skip => [:sessions] do
    get '/employee/sign_in' => 'sessions#new', :as => :new_emoloyee_session
    post '/employee/sign_in' => 'sessions#create', :as => :employee_session
    get '/employee/sign_out' => 'sessions#destroy', :as => :destroy_employee_session
  end

  get 'leave_requests' => "leave_requests#index"
  get 'home/index'

  get 'home/about'

  get 'home/contact'

  get '/dashboard' => 'dashboard#index', as: :dashboard

  get 'reports/index'
  get 'reports/team_comparision' => "reports#team_comparision", as: :team_comparision
  get 'reports/team_highest_score' => "reports#team_highest_score", as: :team_highest_score
  get 'reports/attemted_vs_passed' => "reports#attemted_vs_passed", as: :attemted_vs_passed
  get 'reports/result_employee_list' => "reports#result_employee_list", as: :report_employee_list
  get 'reports/show_exam_attempte/:employee_id' => "reports#show_exam_attempte", as: :show_exam_attempte
  get 'reports/export_to_csv' => "reports#export_to_csv", as: :export_to_csv

  get 'teams/add_members/:id/:employee_id' => "teams#add_members", as: :add_members
  get 'teams/remove_members/:id/:employee_id' => "teams#remove_members", as: :remove_members
  resources :teams

  resources :subjects
  # get  'results/index' => "results#index", as: :index
  get  'results/exam_result/:exam_id' => "results#exam_result", as: :exam_result
  get  'results/employee_result(/:employee_id)' => "results#employee_result", as: :employee_result
  post 'results/filter_result' => "results#filter_result", as: :filter_result
  get  'results/print/:result' => "results#print", as: :print
  get  'results/activate_result/:exam_id' => "results#activate_result", as: :activate_result
  get  'results/inactivate_result/:exam_id' => "results#inactivate_result", as: :inactivate_result
  get  'results/print_team_result/:team_id' => "results#print_team_result", as: :print_team_result

  post 'questions/complete'

  resources :results
  resources :questions
  resources :exams
  resources :switch_days


  post '/employee_report_show' => "reports#employee_report_show", as: :employee_report_show
  get '/employee_report' => "reports#employee_report", as: :employee_report
  get '/start_tracker_timer' => "trackers#start_tracker_timer", as: :start_tracker_timer
  get '/stop_tracker_timer' => "trackers#stop_tracker_timer", as: :stop_tracker_timer
  get '/employee_projects' => "trackers#employee_projects", as: :employee_projects
  get '/attendance' => "employees#attendance_logs", as: :attendance_logs
  #get '/switch_day' => "employees#switch_day", as: :switch_day
  get '/exam/questions/:exam_id' => "questions#start", as: :exam_start
  post '/question/submit/:q_id' => "questions#save_ans", as: :save_ans
  get '/question/save_ans_by_teacher/:q_id/:employee_id' => "questions#save_ans_by_teacher", as: :save_ans_by_teacher

  resources :documents
  get '/profile/:id' => "employees#show", as: :employee_profile
  post '/upload_document/:id' => "employees#upload_document", as: :upload_document
  get 'download/:id' => "documents#download", as: :download_document
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html'
  get '/gen/send_message' => 'general#send_message', as: :general_send_message
  get '/gen/show_message/:m_id' => 'general#show_message', as: :general_show_message
  get '/gen/new_message' => 'general#new_message', as: :general_new_message
  delete '/gen/delete_message/:m_id' => 'general#delete_message', as: :delete_message


  get '/:id/signatures' => "signatures#index", as: :user_signatures
  post '/save_signature/:id' => "signatures#create", as: :save_signature
  get '/signatures/:id/download' => "signatures#download", as: :download_signature
  delete '/signatures/:id' => "signatures#destroy", as: :delete_signature

  get '/employee_benefits' => 'employee_benefits#index', as: :employee_benefits
  post '/employee_benefits/:id/upload_template' => "employee_benefits#upload_template", as: :upload_template
  get '/download_template/:id' => "employee_benefits#download_emp_benefit_doc", as: :download_emp_benefit_doc
  post '/employee_benefits/:id/upload_benefit_doc' => "employee_benefits#upload_benefit_doc", as: :upload_benefit_doc
  delete '/employee_benefit_docs/:id/destroy' => "employee_benefits#delete_emp_benefit_doc", as: :delete_emp_benefit_doc
  get '/employee_benefit_docs/:id' => "employee_benefits#show", as: :show_emp_benefit_doc

  get '/disclosures' => 'disclosures#index', as: :disclosures
  post '/disclosures/:id/upload_disclosure_template' => "disclosures#upload_disclosure_template", as: :upload_disclosure_template
  get '/download_disc_template/:id' => "disclosures#download_disclosure_doc", as: :download_disclosure_doc
  post '/disclosures/:id/upload_disclosure_doc' => "disclosures#upload_disclosure_doc", as: :upload_disclosure_doc
  delete '/disclosures/:id/destroy' => "disclosures#delete_disclosure_doc", as: :delete_disclosure_doc
  get '/disclosures/:id' => "disclosures#show", as: :show_disclosure_doc

  get '/perf_review_template/new' => 'perf_review_templates#new', as: :new_perf_review_template

  get '/request/:reviewer_id/send_review' => 'perf_reviews#new', as: :give_review

  post '/create_perf_reviews/:reviewer_id' => 'perf_reviews#create', as: :create_perf_reviews

  get '/download_perf_review/:id' => 'perf_reviews#download_pdf', as: :download_pdf

  mount ActionCable.server => "/cable"
end

app/models/project_team_member.rb
class ProjectTeamMember < ApplicationRecord
  belongs_to :employee
  belongs_to :project_team
end

app/controllers/project_team_members_controller.rb
class ProjectTeamMembersController < ApplicationController
  def new
    @project_team_member = ProjectTeamMember.new
    if ProjectTeam.find(params[:pt]).project_team_members.includes(:employee).where(employees: { role_id: Role.find_by(role: "team_leader") }).present?
      @emp_team = Employee.joins(:role).where("roles.role in (?)", ["employee", "team_manager"]).not_added
    elsif ProjectTeam.find(params[:pt]).project_team_members.includes(:employee).where(employees: { role_id: Role.find_by(role: "team_manager") }).present?
      @emp_team = Employee.joins(:role).where("roles.role in (?)", ["employee", "team_leader"]).not_added
    else
      @emp_team = Employee.members.not_added
    end

    @team = ProjectTeam.find(params[:pt]).project_team_members

    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @project_team_member = ProjectTeamMember.find(params[:id])
  end

  def index
    @project_team_members = ProjectTeamMember.all
  end

  def show
    @project_team_member = ProjectTeamMember.find(params[:id])
  end

  def create
    @project_team_member = ProjectTeamMember.new(project_team_member_params)
    @project_team_member.save

    if ProjectTeam.find(params[:project_team_member][:project_team_id]).project_team_members.includes(:employee).where(employees: { role_id: Role.find_by(role: "team_leader") }).present?
      @emp_team = Employee.joins(:role).where("roles.role in (?)", ["employee", "team_manager"]).not_added
    elsif ProjectTeam.find(params[:project_team_member][:project_team_id]).project_team_members.includes(:employee).where(employees: { role_id: Role.find_by(role: "team_manager") }).present?
      @emp_team = Employee.joins(:role).where("roles.role in (?)", ["employee", "team_leader"]).not_added
    else
      @emp_team = Employee.members.not_added
    end

    @team = ProjectTeam.find(params[:project_team_member][:project_team_id]).project_team_members

    respond_to do |format|
      format.js
    end
  end

  def update
    @project_team_member = ProjectTeamMember.find(params[:id])
    @project_team_member.update(project_team_member_params)
    redirect_to project_team_members_path
  end

  def destroy
    @project_team_member = ProjectTeamMember.find_by(employee_id: params[:employee_id], project_team_id: params[:project_team_id])
    @project_team_member.destroy

    if ProjectTeam.find(params[:project_team_id]).project_team_members.includes(:employee).where(employees: { role_id: Role.find_by(role: "team_leader") }).present?
      @emp_team = Employee.joins(:role).where("roles.role in (?)", ["employee", "team_manager"]).not_added
    elsif ProjectTeam.find(params[:project_team_id]).project_team_members.includes(:employee).where(employees: { role_id: Role.find_by(role: "team_manager") }).present?
      @emp_team = Employee.joins(:role).where("roles.role in (?)", ["employee", "team_leader"]).not_added
    else
      @emp_team = Employee.members.not_added
    end

    @team = ProjectTeam.find(params[:project_team_id]).project_team_members

    respond_to do |format|
      format.js
    end
  end

  def org_team_chart
    @team_managers = Employee.team_managers
    @team_leaders = Employee.team_leaders
    @project_teams = ProjectTeam.all
  end

  private
    def project_team_member_params
      params.require(:project_team_member).permit(:employee_id, :project_team_id)
    end
end

app/helpers/project_team_members_helper.rb
module ProjectTeamMembersHelper
end

app/views/project_team_members/_all_employees.html.erb
<%= link_to project_team_members_path(project_team_member: { employee_id: emp.id, project_team_id: pt_id}), method: :post, remote: true, class: "available-members" do %>
  <div class="employee-blocks">
    <i class="fa fa-plus" aria-hidden="true"></i>
    <%= emp.name %>
    <span class="pull-right">(<%= emp.user_role %>)</span>
  </div>
<% end %>

app/views/project_team_members/_form.html.erb
Click on Available member to add in Team
<div class="row">
  <div class="col-xs-12 align-center">
    <div class='col-sm-6'> Available Members</div>
    <div class='col-sm-6'> Team Members</div>
  </div>
  <div class="col-sm-6 box-with-all-emp">
    <%= render partial: "all_employees", collection: @emp_team, as: :emp, locals: { pt_id: params[:pt]} %>
  </div>
  <div class="col-sm-6 box-with-selected-emp">
    <%= render partial: "team_employees", collection: @team, as: :emp, locals: { pt_id: params[:pt]} %>
  </div>
</div>

app/views/project_team_members/_team_employees.html.erb
<%= link_to project_team_member_path(emp.id, employee_id: emp.employee.id, project_team_id: pt_id), method: :delete, remote: true, class: "available-members" do %>
  <div class="employee-blocks">
    <i class="fa fa-minus" aria-hidden="true"></i>
    <%= emp.employee.name %>
    <span class="pull-right">(<%= emp.employee.user_role %>)</span>
  </div>
<% end %>

app/views/project_team_members/create.js.erb
$(".box-with-all-emp").html("<%= escape_javascript(render partial: 'all_employees', collection: @emp_team, as: :emp, locals: { pt_id: params[:project_team_member][:project_team_id] }) %>");
$(".box-with-selected-emp").html("<%= escape_javascript(render partial: 'team_employees', collection: @team, as: :emp, locals: { pt_id: params[:project_team_member][:project_team_id] }) %>");

app/views/project_team_members/destroy.js.erb
$(".box-with-all-emp").html("<%= escape_javascript(render partial: 'all_employees', collection: @emp_team, as: :emp, locals: { pt_id: params[:project_team_id] }) %>");
$(".box-with-selected-emp").html("<%= escape_javascript(render partial: 'team_employees', collection: @team, as: :emp, locals: { pt_id: params[:project_team_id] }) %>");
$("li.team_member_<%= params[:id] %>").hide();

app/views/project_team_members/edit.html.erb
<h1>Editing Project Team Member</h1>

<%= render 'form', project_team_member: @project_team_member %>

<%= link_to 'Show', @project_team_member %> |
<%= link_to 'Back', project_team_members_path %>

app/views/project_team_members/index.html.erb
<h1>ProjectTeamMembers#index</h1>
<p>Find me in app/views/project_team_members/index.html.erb</p>
<div class="row">
  <div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
    <div class="table-responsive">
      <p id="notice"></p>
      <h1>Project Team</h1>
      <% if @project_team_members.present? %>
        <table class="table table-bordered table-hover table-striped">
          <thead>
            <tr>
              <th>Title</th>
              <th>project</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @project_team_members.each do |team| %>
              <tr>
                <td><%= team.name %></td>
                <td>
                  <ol>
                    <% team.project_title.each do |name| %>
                      <li><%= name %></li>
                    <% end %>
                  </ol>
                </td>
                  <td><%= link_to 'Show', project_team_path(team) %></td>
                  <td><%= link_to 'Edit', edit_project_team_path(team
                  ) %></td>
                  <td><%#= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        You don't have any exam 
      <% end %>
      <br>
      <%= link_to 'New Exam', new_exam_path if current_employee.user_role == 'teacher' %>
    </div>
  </div>
</div>

app/views/project_team_members/new.html.erb
<div class="row clearfix">
  <div class="col-sm-12">
    <div class="card">
      <div class="header">
        <h2>New Project Team member</h2>
      </div>
      <div class="body">
        <div class="row clearfix">
          <div class="col-xs-12">
            <%= render 'form', project_team_member: @project_team_member %>
          </div>
        </div>
        <%= link_to 'Back', project_teams_path %>
      </div>
    </div>
  </div>
</div>

app/views/project_team_members/new.js.erb
alert();
$("#editBlocks").html("<%= escape_javascript(render 'form', project_team_member: @project_team_member) %>")
$("#editTeamModal").modal("show");

app/views/project_team_members/org_team_chart.html.erb
<div class="row clearfix">
  <div class="col-xs-12">
    <div class="card">
      <div class="header">
        <h2>Org Chart</h2>
      </div>
      <div class="body">
        <div class="row clearfix">
          <div class="col-xs-12">
            <table class="table table-bordered">
              <tbody>
                <tr>
                  <% @project_teams.each do |team| %>
                    <td>
                      <div>
                        <p class="pull-left">
                          <strong> Team: </strong><%= team.name %>
                        </p>
                        <p class="pull-right">
                          <%= link_to "Edit", new_project_team_member_path(pt: team), remote: true, class: "btn bg-blue-grey waves-effect" %>
                        </p>
                      </div>
                      <div class="clearfix"></div>
                      <div>
                        <% team.project_team_members.includes(:employee).order("employees.role_id asc").each_with_index do |emp, index| %>
                          <li class="box-shade <%= 'leader-color' if emp.employee.user_role != 'employee' %> team_member_<%= emp.id %>" style="list-style-type: none;">
                            <%= emp.employee.name %>
                            (<%= emp.employee.user_role %>)
                            <span class="pull-right">
                              <%= link_to "X", project_team_member_path(emp.id, employee_id: emp.employee.id, project_team_id: team.id), method: :delete, remote: true, class: "white" %>
                            </span>
                          </li>
                        <% end %>
                      </div>
                    </td>
                  <% end %>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <%= link_to 'New Project', new_project_path %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="editTeamModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="defaultModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <div class="row clearfix">
          <div class="col-xs-12" id="editBlocks">
            <%#= render 'form', project_team_member: @project_team_member %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-link waves-effect">SAVE CHANGES</button>
        <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
      </div>
    </div>
  </div>
</div>

app/views/project_team_members/show.html.erb
<h1>ProjectTeamMembers#show</h1>
<p>Find me in app/views/project_team_members/show.html.erb</p>