config/routes.rb
Rails.application.routes.draw do


  resources :perf_review_requests
  resources :perf_reviews
  resources :ques_answs
  resources :perf_review_catgs do
    resources :review_catg_quests, only: [:new, :create]
  end

  resources :review_catg_quests, only: [:edit, :update, :destroy]

  resources :events
  root 'home#index'
  resources :project_team_members
  get "/org_team_chart" => "project_team_members#org_team_chart", as: :org_team_chart
  resources :project_teams
  resources :trackers
  resources :projects
  resources :leaves
  resources :issues
  resources :experiences
  resources :employees, except: [:show], path: '/users'
  resources :leave_work_assign
  resources :roles

  devise_for :employees, controllers: {
    sessions: 'employees/sessions',
    registrations: 'employees/registrations',
    passwords: 'employees/passwords',
  }

  devise_for :employee, :controllers => {:sessions => 'sessions'}, :skip => [:sessions] do
    get '/employee/sign_in' => 'sessions#new', :as => :new_emoloyee_session
    post '/employee/sign_in' => 'sessions#create', :as => :employee_session
    get '/employee/sign_out' => 'sessions#destroy', :as => :destroy_employee_session
  end

  get 'leave_requests' => "leave_requests#index"
  get 'home/index'

  get 'home/about'

  get 'home/contact'

  get '/dashboard' => 'dashboard#index', as: :dashboard

  get 'reports/index'
  get 'reports/team_comparision' => "reports#team_comparision", as: :team_comparision
  get 'reports/team_highest_score' => "reports#team_highest_score", as: :team_highest_score
  get 'reports/attemted_vs_passed' => "reports#attemted_vs_passed", as: :attemted_vs_passed
  get 'reports/result_employee_list' => "reports#result_employee_list", as: :report_employee_list
  get 'reports/show_exam_attempte/:employee_id' => "reports#show_exam_attempte", as: :show_exam_attempte
  get 'reports/export_to_csv' => "reports#export_to_csv", as: :export_to_csv

  get 'teams/add_members/:id/:employee_id' => "teams#add_members", as: :add_members
  get 'teams/remove_members/:id/:employee_id' => "teams#remove_members", as: :remove_members
  resources :teams

  resources :subjects
  # get  'results/index' => "results#index", as: :index
  get  'results/exam_result/:exam_id' => "results#exam_result", as: :exam_result
  get  'results/employee_result(/:employee_id)' => "results#employee_result", as: :employee_result
  post 'results/filter_result' => "results#filter_result", as: :filter_result
  get  'results/print/:result' => "results#print", as: :print
  get  'results/activate_result/:exam_id' => "results#activate_result", as: :activate_result
  get  'results/inactivate_result/:exam_id' => "results#inactivate_result", as: :inactivate_result
  get  'results/print_team_result/:team_id' => "results#print_team_result", as: :print_team_result

  post 'questions/complete'

  resources :results
  resources :questions
  resources :exams
  resources :switch_days


  post '/employee_report_show' => "reports#employee_report_show", as: :employee_report_show
  get '/employee_report' => "reports#employee_report", as: :employee_report
  get '/start_tracker_timer' => "trackers#start_tracker_timer", as: :start_tracker_timer
  get '/stop_tracker_timer' => "trackers#stop_tracker_timer", as: :stop_tracker_timer
  get '/employee_projects' => "trackers#employee_projects", as: :employee_projects
  get '/attendance' => "employees#attendance_logs", as: :attendance_logs
  #get '/switch_day' => "employees#switch_day", as: :switch_day
  get '/exam/questions/:exam_id' => "questions#start", as: :exam_start
  post '/question/submit/:q_id' => "questions#save_ans", as: :save_ans
  get '/question/save_ans_by_teacher/:q_id/:employee_id' => "questions#save_ans_by_teacher", as: :save_ans_by_teacher

  resources :documents
  get '/profile/:id' => "employees#show", as: :employee_profile
  post '/upload_document/:id' => "employees#upload_document", as: :upload_document
  get 'download/:id' => "documents#download", as: :download_document
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html'
  get '/gen/send_message' => 'general#send_message', as: :general_send_message
  get '/gen/show_message/:m_id' => 'general#show_message', as: :general_show_message
  get '/gen/new_message' => 'general#new_message', as: :general_new_message
  delete '/gen/delete_message/:m_id' => 'general#delete_message', as: :delete_message


  get '/:id/signatures' => "signatures#index", as: :user_signatures
  post '/save_signature/:id' => "signatures#create", as: :save_signature
  get '/signatures/:id/download' => "signatures#download", as: :download_signature
  delete '/signatures/:id' => "signatures#destroy", as: :delete_signature

  get '/employee_benefits' => 'employee_benefits#index', as: :employee_benefits
  post '/employee_benefits/:id/upload_template' => "employee_benefits#upload_template", as: :upload_template
  get '/download_template/:id' => "employee_benefits#download_emp_benefit_doc", as: :download_emp_benefit_doc
  post '/employee_benefits/:id/upload_benefit_doc' => "employee_benefits#upload_benefit_doc", as: :upload_benefit_doc
  delete '/employee_benefit_docs/:id/destroy' => "employee_benefits#delete_emp_benefit_doc", as: :delete_emp_benefit_doc
  get '/employee_benefit_docs/:id' => "employee_benefits#show", as: :show_emp_benefit_doc

  get '/disclosures' => 'disclosures#index', as: :disclosures
  post '/disclosures/:id/upload_disclosure_template' => "disclosures#upload_disclosure_template", as: :upload_disclosure_template
  get '/download_disc_template/:id' => "disclosures#download_disclosure_doc", as: :download_disclosure_doc
  post '/disclosures/:id/upload_disclosure_doc' => "disclosures#upload_disclosure_doc", as: :upload_disclosure_doc
  delete '/disclosures/:id/destroy' => "disclosures#delete_disclosure_doc", as: :delete_disclosure_doc
  get '/disclosures/:id' => "disclosures#show", as: :show_disclosure_doc

  get '/perf_review_template/new' => 'perf_review_templates#new', as: :new_perf_review_template

  get '/request/:reviewer_id/send_review' => 'perf_reviews#new', as: :give_review

  post '/create_perf_reviews/:reviewer_id' => 'perf_reviews#create', as: :create_perf_reviews

  get '/download_perf_review/:id' => 'perf_reviews#download_pdf', as: :download_pdf

  mount ActionCable.server => "/cable"
end

app/controllers/reports_controller.rb
require "csv"

class ReportsController < ApplicationController
  def index
  end

  def team_comparision
  end

  def employee_report
  end

  def employee_report_show
    @project_id = params[:report][:project_id]
    @selected_start_date =  params[:start_date][:start_date].to_date.beginning_of_day if params[:start_date][:start_date].present?
    @selected_end_date =  params[:end_date][:end_date].to_date.end_of_day if params[:end_date][:end_date].present?
    @project = Project.find(@project_id)
    @project_team_id = @project.assigned_to
    @project_team = ProjectTeam.find(@project_team_id)
    @project_team_members = @project_team.project_team_members

    respond_to do |format|
      format.js 
    end

  end

  def team_highest_score
    data_table = GoogleVisualr::DataTable.new
    data_table.new_column('string', 'Exam & Team')
    data_table.new_column('number', 'Highest Marks')

    data_table.add_rows(Result.all.group_by(&:exam_id).count)

    Result.where("created_at > ?", 1.years.ago).group_by(&:exam_id).map { |id, results| results.max_by(&:correct_ans) }.each_with_index do |result, index|
      data_table.set_cell(index, 0, "#{result.exam.title} from Team  #{result.exam.team.name}")
      data_table.set_cell(index, 1, result.correct_ans)
    end

    opts   = { :width => 500, :height => 300, :title => 'Exams With highest Score', :hAxis => { :title => 'Exam with Team', :titleTextStyle => { :color => '#3377dd' } }, colors: ['#1B9E77', '#D95F02'], vAxis: { title: "Score", :titleTextStyle => { :color => '#44dd88' } } }
    @chart = GoogleVisualr::Interactive::ColumnChart.new(data_table, opts)    
  end

  def attemted_vs_passed
    data_table = GoogleVisualr::DataTable.new
    data_table.new_column('string', 'Exam & Team')
    data_table.new_column('number', 'Attemted Employees')
    data_table.new_column('number', 'Passed Employees')
    data_table.add_rows(Result.all.group_by(&:exam_id).count)

    Exam.joins(:results).where("results.created_at > ?", 1.years.ago).where.not(results: {exam_id: nil}).uniq.each_with_index do |exam, index|
      data_table.set_cell(index, 0, "#{exam.title} From Team #{exam.team.name}")
      data_table.set_cell(index, 1, exam.results.count)
      data_table.set_cell(index, 2, exam.results.select{ |result| (result.correct_ans >= exam.cut_off_marks.to_f) }.count )
    end

    opts   = { :width => 500, :height => 300, :title => 'Attemted Employees vs Passed Employees', :legend => 'bottom', colors: ["#4285F4", "#169D75"], hAxis: { title: "Exam with Team", :titleTextStyle => { :color => '#3388ff' } }, vAxis: { title: "Employees", :titleTextStyle => { :color => '#44dd88' }  }  }
    @chart = GoogleVisualr::Interactive::LineChart.new(data_table, opts)
  end

  def result_employee_list
    # @employees = employee.students.joins([results: :exam], :responses, :teams).group("employees.id")
    # employee.students.includes(:exams, :results).where.not(results: {exam_id: nil}).zip
    # employee.students.includes(:exams, :results).where(results: {exam_id: nil})
    @employees = Employee.employees.eager_load(:exams, :results)
  end

  def show_exam_attempte
    @response = Response.eager_load(:question, :employee).where("employees.id = ? and correct_ans = false", params[:employee_id]).group("response.exam_id")
    @employee = employee.find(params[:employee_id])
    @responses = Response.where(employee_id: params[:employee_id], correct_ans: false)
    # @questions = Question.eager_load(:responses).select("responses.*").where("responses.correct_ans = false and responses.employee_id = ?", params[:employee_id])
  end

  def export_to_csv
    @employees = Employee.employees.eager_load(:exams, :results)

    respond_to do |format|
      format.csv { send_data @employees.to_csv, filename: "employees-attempts-#{Date.today}.csv" }
    end
  end

end

app/views/reports/_employee_review.html.erb
<div class="panel panel-default">
	<div class="panel-heading clearfix">
	<div class="row col-md-12 col-md-offset-0 custyle">
	<table class="table table-striped ">
    <thead>
      <tr>
        <th>Name</th>
        <th>Total Task</th>
        <th>Team</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%=project_team_member.employee.first_name%>  <%=project_team_member.employee.last_name%></td>
        <% if selected_start_date && selected_end_date %>
    	    <% @trackers = project_team_member.employee.trackers.where(:created_at => selected_start_date..selected_end_date) %>
        <%else%>
        	<% @trackers = project_team_member.employee.trackers %>
        <% end %>
        <td><%=@trackers.count rescue 0 %></td>
        <td><%=team.name%></td>
      </tr>
      </tbody>
      
  </table>
		</div>
		<div class="pull-right">
			<button class="btn btn-default collapsed" type="button" data-toggle="collapse" data-target="#collapse<%=project_team_member.employee_id%>" aria-expanded="false" aria-controls="collapse<%=project_team_member.employee_id%>"><i class="fa fa-bars"></i></button>
		</div>
	</div>
	<div class="panel-body collapse" id="collapse<%=project_team_member.employee_id%>" aria-expanded="false" style="height: 30px;">
	<% if project_team_member.employee.trackers.present? %>
		<table class="table table-striped">
	    <thead>
	      <tr>
	        <th>Date : </th>
	        <th>Task Title :</th>
	        <th>Status</th>
	        <th>Total Time(hh:mm:ss)</th>
	      </tr>
	    </thead>
	    <tbody>
	      <%= render partial: "task_list", collection:@trackers, as: :tracker %>
	    </tbody>
	  </table>
	  <% else %>
	  <h4> No Task(s) Found ! </h4>
	  <% end %>
	</div>
</div>
    

app/views/reports/_task_list.html.erb
<%

    logs=tracker.tracker_logs
    if tracker.tracker_logs.count >= 2 
      start_time = tracker.created_at.to_time
      end_time =  tracker.tracker_logs.where(status: "STOP").last.created_at.to_time
    else
      start_time = 0
      end_time  = 0
    end
      if start_time.present? && end_time.present?
        @minutes = (start_time -  end_time) / 60.abs

      end

         total_seconds = @minutes * 60
         @hours = total_seconds / (60 * 60)
         @minutes = (total_seconds / 60) % 60
         @seconds = total_seconds % 60
%>

<tr>
  <td><%=tracker.created_at%></td>
  <td><%=tracker.title%></td>

  <td>
  <%if tracker.tracker_logs.count.even?%>
    <span class="label label-warning">Stopped</span>
    <% else %>
    <span class="label label-info">In Progress</span>
    <% end %>
  </td>

  <td><%=  @hours.floor.positive? ? @hours.floor : "00"%> : <%=  @minutes.floor.positive? ? @minutes.floor : "00"%> : <%=  @seconds.floor.positive? ? @seconds.floor : "00"%>  </td>
</tr>

app/views/reports/attemted_vs_passed.html.erb
<% content_for :head do %>
  <script src='https://www.google.com/jsapi'></script>
<% end %>
<div class="row clearfix">
  <div class="col-sm-12">
    <div class="card">
      <div class="header">
        <h2>Employee - Exams</h2>
      </div>
      <div class="body">
        <div id='chart'></div>
        <%= render_chart @chart, 'chart' %>
      </div>
    </div>
  </div>
</div>

app/views/reports/employee_report.html.erb
<div class="row clearfix">
  <div class="col-sm-12">
    <div class="card">
      <div class="header">
        <h2>Employee Report</h2>
      </div>
      <div class="body">
        <div class="row clearfix">
          <div class="col-sm-6 col-sm-offset-2 col-xs-12">
            <%= form_for(:report, :url => employee_report_show_path, html: { class: "form-horizontal"}, remote: true) do |f| %>
            <div class="col-xs-12">
              <div class="form-group form-float">
                <div class="form-line">
                  <%= f.label :project_id, class: "form-label" %>
                  <%= f.select :project_id, Project.all.collect {|p| [ p.name, p.id ] }, {}, class: "form-control" %>
                </div>
              </div>
            </div>
            <div class="col-xs-12">
              <div class="form-group form-float">
                <div class="form-line">
                  <%= f.label :start_date, class: "form-label" %>
                  <%= date_field(:start_date,:start_date, class: "form-control") %>
                </div>
              </div>
            </div>
            <div class="col-xs-12">
              <div class="form-group form-float">
                <div class="form-line">
                  <%= f.label :end_date, class: "form-label" %>
                  <%= date_field(:end_date,:end_date, class: "form-control") %>
                </div>
              </div>
            </div>
            <div class="actions demo-button-sizes">
              <div class="col-xs-6 col-sm-3 col-md-2 col-lg-2">
                <%= f.submit "Show Report", class: "btn bg-cyan waves-effect" %>
              </div>
            </div>
            <% end %>            
          </div>
        </div>
        <%= link_to 'Back', leaves_path %>
      </div>
    </div>
  </div>
</div>

<hr class="style13">
<div class="row clearfix">
  <div class="col-sm-12">
    <div class="card">
      <div class="header">
        <h2>Employee Report</h2>
      </div>
      <div class="body">
        <h3>Employee List </h3>
        <div class="add_report_list">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/employee_report_show.js.erb
$(".add_report_list").html("<%= escape_javascript(render partial: 'employee_review', collection: @project_team_members, as: :project_team_member,locals: { team: @project_team,member: @project_team_members, project: @project, selected_start_date: @selected_start_date, selected_end_date: @selected_end_date }) %>");

app/views/reports/index.html.erb
<h1>Reports#index</h1>
<p>Find me in app/views/reports/index.html.erb</p>

app/views/reports/result_employee_list.html.erb
<div class="row clearfix">
  <div class="col-sm-12">
    <div class="card">
      <div class="header">
        <h2>Employee - Exams</h2>
      </div>
      <div class="body">

        <div class="table-responsive">
          <p class="pull-right">
            <%= link_to "Export to CSV", export_to_csv_path(format: :csv) %>
          </p>
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Exam</th>
                <th>Attemted?</th>
              </tr>
            </thead>
            <tbody>
              <% @employees.each do |employee| %>
                <% employee.exams.each do |exam| %>
                  <% attemted = exam.is_attemted_by(employee) %>
                  <tr>
                    <td> <%= attemted ? link_to(employee.fullname, show_exam_attempte_path(employee)) : employee.fullname %> </td>
                    <td> <%= exam.title %> </td>
                    <td> <%= attemted %> </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/show_exam_attempte.html.erb
<h3>User: <%= @employee.fullname %></h3>
<table class="table table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th>Exam</th>
      <th>Question</th>
      <th>Users ans</th>
      <th>Correct ans</th>
      <th>Options</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @responses.each do |res| %>
      <tr>
        <td><%= res.question.exam.title %></td>
        <td><%= res.question.question %></td>
        <td><%= res.answer %></td>
        <td><%= res.question.answer %></td>
        <td><%= res.question.options.gsub(/(\{|\}|")/, "").gsub(/=>/, ". ").split(",").join("  &nbsp;<br/>").html_safe if res.question.question_type == "Choices" %></td>
        <td id="response_<%= res.id %>"><%= link_to "Mark as Correct", save_ans_by_teacher_path(res.question, @employee), remote: true, data: { confirm: "Are you sure you want to Make this Ans as correct Answer?" } if res.question.question_type != "Choices"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr/>

app/views/reports/team_comparision.html.erb
<h1>Reports#team_comparision</h1>
<p>Find me in app/views/reports/team_comparision.html.erb</p>

app/views/reports/team_highest_score.html.erb
<% content_for :head do %>
  <script src='https://www.google.com/jsapi'></script>
<% end %>
<div class="row clearfix">
  <div class="col-sm-12">
    <div class="card">
      <div class="header">
        <h2>Employee - Exams</h2>
      </div>
      <div class="body">
        <%= content_for(:body_attributes, 'data-no-turbolink') %>
        <div id='chart'></div>
        <%= render_chart @chart, 'chart' %>
      </div>
    </div>
  </div>
</div> 